import Head from 'next/head';
import Image from 'next/image';
import { useSelector, useDispatch } from 'react-redux';
import { IRootState } from '../redux/types';
import styles from '../styles/Home.module.css';

export default function Home() {
  const dispatch = useDispatch();
  const { counter } = useSelector((state: IRootState) => state.first);
  const list = useSelector((state: IRootState) => state.second);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>
          <button type="button" onClick={() => dispatch({ type: 'DECREMENT' })}>
            -1
          </button>
          <h1>{counter}</h1>
          <button type="button" onClick={() => dispatch({ type: 'INCREMENT' })}>
            +1
          </button>
        </div>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <ul>
            {list.map((item: any) => (
              <li key={item.name}>
                {item.id} - {item.name}
              </li>
            ))}
          </ul>
          <button type="button" onClick={() => dispatch({ type: 'ADD_ITEM' })}>
            Add item
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
